stages:
  - build
  - test
  - docker

variables:
  GO_VERSION: "1.22"

# Шаг 1 — Сборка
build_job:
  stage: build
  image: golang:${GO_VERSION}
  script:
    - go mod tidy
    - go build -o app .
  artifacts:
    paths:
      - app

# Шаг 2 — Тестирование
test_job:
  stage: test
  image: golang:${GO_VERSION}
  script:
    - go test ./tests/

# Шаг 3 — Создание Docker-образа
docker_build_job:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
